version: '3.8'

services:
  snapchat-bot:
    build:
      context: .
      dockerfile: Dockerfile-vnc
    image: snapchat-bot-vnc
    ports:
      - "6080:6080"  # noVNC web interface
      - "5900:5900"  # VNC server
    volumes:
      - ./driver_user:/app/driver_user  # Persist Chrome profile
    environment:
      - DISPLAY=:99
      - PYTHONUNBUFFERED=1
    shm_size: 4g
    container_name: snapchat-bot-vnc
    stop_signal: SIGTERM  # Ensure graceful shutdown
    stop_grace_period: 10s  # Allow time for cleanup